import 'sw/registerSW'
import './Component/Layout/Layout.css'
import './Component/Navigation/Navigation'
import './Page/Departures/Departures'
import './Page/Trip/Trip'
import './Page/Favorites/Favorites'
