name: 'Monorepo Split'

on:
  push:
    branches:
      - split

jobs:
  split_monorepo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - snappy-renderer
          - snappy-renderer-smarty
          - snappy-core

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@master"

      - name: Monorepo Split of ${{ matrix.package }}
        uses: symplify/github-action-monorepo-split@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package-directory: 'packages/${{ matrix.package }}'
          split-repository-organization: 'construct-blue'
          split-repository-name: '${{ matrix.package }}'
          tag: ${{ steps.previous_tag.outputs.tag }}
          user-name: "robertkleinschuster"
          user-email: "github@kleinschuster.de"