name: 'Packages Split'

on:
  push:
    branches:
      - split
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  ORG: 'construct-blue'
  NAME: 'robertkleinschuster'
  EMAIL: 'github@kleinschuster.de'

jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          -
            local_path: 'snappy-core'
            split_repository: 'snappy-core'
          -
            local_path: 'snappy-renderer'
            split_repository: 'snappy-renderer'
          -
            local_path: 'snappy-renderer-smarty'
            split_repository: 'snappy-renderer-smarty'

    steps:
      -   uses: actions/checkout@v2

      # no tag
      -
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.1"
        with:
          # ↓ split "packages/easy-coding-standard" directory
          package_directory: 'packages/${{ matrix.package.local_path }}'

          # ↓ into https://github.com/symplify/easy-coding-standard repository
          repository_organization: ${{ env.ORG }}
          repository_name: '${{ matrix.package.split_repository }}'

          # [optional, with "github.com" as default]
          #repository_host: git.private.com:1234

          # ↓ the user signed under the split commit
          user_name: ${{ env.NAME }}
          user_email: ${{ env.EMAIL }}

      # with tag
      -
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.1"
        with:
          tag: ${GITHUB_REF#refs/tags/}

          # ↓ split "packages/easy-coding-standard" directory
          package_directory: 'packages/${{ matrix.package.local_path }}'

          # ↓ into https://github.com/symplify/easy-coding-standard repository
          repository_organization: ${{ env.ORG }}
          repository_name: '${{ matrix.package.split_repository }}'

          # [optional, with "github.com" as default]
          #repository_host: git.private.com:1234

          # ↓ the user signed under the split commit
          user_name: ${{ env.NAME }}
          user_email: ${{ env.EMAIL }}